name = "LocalSearch"
uuid = "3edf9609-13f2-4288-b0a3-8bd6d521158e"
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
llama_cpp_jll = "98bd2d0b-bc7c-583a-ba54-7299b0ad0e7f"
sqlite_vec_jll = "baba3ab0-b101-5c6b-81c2-6f96346aa768"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
